/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoApisRouteImport } from './routes/demo.apis'
import { Route as DemoImpactRouteImport } from './routes/demo.impact'
import { Route as DemoMigrationRouteImport } from './routes/demo.migration'
import { Route as DemoRunsRouteImport } from './routes/demo.runs'
import { Route as DemoSettingsRouteImport } from './routes/demo.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApisRoute = DemoApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => DemoRoute,
} as any)
const DemoImpactRoute = DemoImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => DemoRoute,
} as any)
const DemoMigrationRoute = DemoMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => DemoRoute,
} as any)
const DemoRunsRoute = DemoRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSettingsRoute = DemoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/apis': typeof DemoApisRoute
  '/demo/impact': typeof DemoImpactRoute
  '/demo/migration': typeof DemoMigrationRoute
  '/demo/runs': typeof DemoRunsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/apis': typeof DemoApisRoute
  '/demo/impact': typeof DemoImpactRoute
  '/demo/migration': typeof DemoMigrationRoute
  '/demo/runs': typeof DemoRunsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo': typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/apis': typeof DemoApisRoute
  '/demo/impact': typeof DemoImpactRoute
  '/demo/migration': typeof DemoMigrationRoute
  '/demo/runs': typeof DemoRunsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/demo/apis'
    | '/demo/impact'
    | '/demo/migration'
    | '/demo/runs'
    | '/demo/settings'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/apis'
    | '/demo/impact'
    | '/demo/migration'
    | '/demo/runs'
    | '/demo/settings'
    | '/demo'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/demo/apis'
    | '/demo/impact'
    | '/demo/migration'
    | '/demo/runs'
    | '/demo/settings'
    | '/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/apis': {
      id: '/demo/apis'
      path: '/apis'
      fullPath: '/demo/apis'
      preLoaderRoute: typeof DemoApisRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/impact': {
      id: '/demo/impact'
      path: '/impact'
      fullPath: '/demo/impact'
      preLoaderRoute: typeof DemoImpactRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/migration': {
      id: '/demo/migration'
      path: '/migration'
      fullPath: '/demo/migration'
      preLoaderRoute: typeof DemoMigrationRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/runs': {
      id: '/demo/runs'
      path: '/runs'
      fullPath: '/demo/runs'
      preLoaderRoute: typeof DemoRunsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/settings': {
      id: '/demo/settings'
      path: '/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof DemoSettingsRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoApisRoute: typeof DemoApisRoute
  DemoImpactRoute: typeof DemoImpactRoute
  DemoMigrationRoute: typeof DemoMigrationRoute
  DemoRunsRoute: typeof DemoRunsRoute
  DemoSettingsRoute: typeof DemoSettingsRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoApisRoute: DemoApisRoute,
  DemoImpactRoute: DemoImpactRoute,
  DemoMigrationRoute: DemoMigrationRoute,
  DemoRunsRoute: DemoRunsRoute,
  DemoSettingsRoute: DemoSettingsRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
