export type Status =
	| "Analyzing"
	| "PRs opened"
	| "Merged"
	| "Needs review"
	| "Up to date"
	| "Update available";

export const changes = [
	{
		api: "orders-service",
		summary: "Order total response shape changed",
		breaking: 3,
		services: 4,
		status: "Needs review" as Status,
		time: "12 min ago",
	},
	{
		api: "Firebase Cloud Messaging",
		summary: "Legacy API migrated to HTTP v1",
		breaking: 6,
		services: 3,
		status: "PRs opened" as Status,
		time: "1h ago",
	},
	{
		api: "AWS SDK",
		summary: "Modular client migration from v2 to v3",
		breaking: 14,
		services: 7,
		status: "Analyzing" as Status,
		time: "3h ago",
	},
	{
		api: "Google Maps",
		summary: "Marker replaced by AdvancedMarkerElement",
		breaking: 2,
		services: 2,
		status: "Merged" as Status,
		time: "Yesterday",
	},
	{
		api: "OpenAI SDK",
		summary: "Client initialization and response API changed",
		breaking: 8,
		services: 5,
		status: "Merged" as Status,
		time: "Sep 19",
	},
];

export const apis = [
	{
		name: "orders-service",
		type: "Internal REST",
		owner: "orders-service",
		current: "v2.8.1",
		latest: "v2.9.0",
		consumers: 4,
		source: "openapi.yaml",
		status: "Update available" as Status,
	},
	{
		name: "checkout-web",
		type: "Internal REST",
		owner: "checkout-web",
		current: "v1.14.2",
		latest: "v1.14.2",
		consumers: 2,
		source: "/api/openapi.json",
		status: "Up to date" as Status,
	},
	{
		name: "Firebase Cloud Messaging",
		type: "External SDK",
		owner: "notification-service",
		current: "legacy",
		latest: "HTTP v1",
		consumers: 3,
		source: "npm registry",
		status: "Update available" as Status,
	},
	{
		name: "AWS SDK",
		type: "External SDK",
		owner: "platform",
		current: "v2.1492",
		latest: "v3.645",
		consumers: 7,
		source: "npm / Maven",
		status: "Update available" as Status,
	},
	{
		name: "Google Maps",
		type: "External SDK",
		owner: "checkout-web",
		current: "Marker",
		latest: "AdvancedMarker",
		consumers: 2,
		source: "npm registry",
		status: "Update available" as Status,
	},
	{
		name: "OpenAI SDK",
		type: "External SDK",
		owner: "ai-platform",
		current: "v3.3.0",
		latest: "v4.68.1",
		consumers: 5,
		source: "npm / NuGet",
		status: "Up to date" as Status,
	},
	{
		name: "iyzico",
		type: "External SDK",
		owner: "payments",
		current: "v2.0.61",
		latest: "v2.0.64",
		consumers: 2,
		source: "npm registry",
		status: "Up to date" as Status,
	},
	{
		name: "Trendyol Partner API",
		type: "External SDK",
		owner: "marketplace",
		current: "v1",
		latest: "v2",
		consumers: 3,
		source: "OpenAPI URL",
		status: "Update available" as Status,
	},
	{
		name: "catalog-graph",
		type: "GraphQL",
		owner: "catalog-service",
		current: "sha.912ac",
		latest: "sha.912ac",
		consumers: 6,
		source: "schema.graphql",
		status: "Up to date" as Status,
	},
];

export const services = [
	{
		name: "checkout-web",
		language: "TypeScript",
		framework: "Next.js",
		files: 6,
		status: "PR #184 opened",
		tone: "success",
		confidence: "98%",
	},
	{
		name: "invoice-service",
		language: "Java",
		framework: "Spring Boot",
		files: 4,
		status: "PR #92 opened",
		tone: "success",
		confidence: "94%",
	},
	{
		name: "notification-service",
		language: "C#",
		framework: ".NET 8",
		files: 2,
		status: "Needs review",
		tone: "warning",
		confidence: "76%",
	},
	{
		name: "fulfillment-worker",
		language: "TypeScript",
		framework: "Node.js",
		files: 3,
		status: "PR #47 opened",
		tone: "success",
		confidence: "96%",
	},
];

export const runs = [
	{
		date: "Sep 22, 21:58",
		trigger: "Schema change",
		api: "orders-service",
		services: 4,
		result: "Needs review",
		duration: "4m 38s",
		cost: "$1.84",
	},
	{
		date: "Sep 22, 19:42",
		trigger: "SDK release",
		api: "Firebase Cloud Messaging",
		services: 3,
		result: "PRs opened",
		duration: "7m 12s",
		cost: "$2.31",
	},
	{
		date: "Sep 22, 17:05",
		trigger: "SDK release",
		api: "AWS SDK",
		services: 7,
		result: "Analyzing",
		duration: "12m 04s",
		cost: "$4.86",
	},
	{
		date: "Sep 21, 14:20",
		trigger: "SDK release",
		api: "Google Maps",
		services: 2,
		result: "Merged",
		duration: "3m 51s",
		cost: "$1.22",
	},
	{
		date: "Sep 19, 09:14",
		trigger: "SDK release",
		api: "OpenAI SDK",
		services: 5,
		result: "Merged",
		duration: "8m 19s",
		cost: "$3.47",
	},
	{
		date: "Sep 17, 16:32",
		trigger: "Schema change",
		api: "iyzico",
		services: 2,
		result: "Merged",
		duration: "2m 48s",
		cost: "$0.94",
	},
	{
		date: "Sep 15, 11:06",
		trigger: "Schema change",
		api: "Trendyol Partner API",
		services: 3,
		result: "Needs review",
		duration: "6m 15s",
		cost: "$2.08",
	},
];
